buildscript {
    ext.kotlin_version = '1.9.22' // Latest stable version
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1' // Latest stable version of AGP
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}

/**
 * The allprojects block is where you configure the repositories and dependencies used by all
 * modules in your project, such as third-party plugins or libraries. However, you should configure
 * module-specific dependencies in each module-level build.gradle file.
 */

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
