plugins {
    id 'com.android.library'
}

android {
    namespace = "com.mojang.minecraftpe"
    compileSdk 35 // Android 15

    defaultConfig {
        minSdk 25

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        targetSdk 35
    }
    testOptions {
        targetSdk 35
    }
}

dependencies {
    compileOnly 'com.google.firebase:firebase-iid:21.1.0'
    compileOnly 'com.google.firebase:firebase-common:20.0.0'
    compileOnly 'com.google.android.gms:play-services-tasks:17.2.1'
}

tasks.withType(org.gradle.api.tasks.compile.JavaCompile).configureEach {
    options.compilerArgs.add("-Xlint:-options")
}

String getSdkPath() {
    File localPropertiesFile = new File(project.rootDir, "local.properties")
    Properties localProperties = new Properties()
    localProperties.load(new FileReader(localPropertiesFile))
    return localProperties.getProperty("sdk.dir")
}

String d8Executable() {
    def buildToolsVersion = "36.0.0" // Check you version

    def sdkPath = getSdkPath()
    def buildToolsDir = "${sdkPath}/build-tools/${buildToolsVersion}/"
    return System.properties['os.name'].toLowerCase().contains("windows") ?
            "${buildToolsDir}d8.bat" : "${buildToolsDir}d8"
}

def classesDir = layout.buildDirectory.dir("intermediates/javac/debug/compileDebugJavaWithJavac/classes")
        .get().asFile.absolutePath
def outputDir = new File(rootDir, "endercore/src/main/assets/endercore/android").absolutePath
def agentMainTempOutputDir = layout.buildDirectory.dir("d8temp_agent_main")
def crackedLicenseTempOutputDir = layout.buildDirectory.dir("d8temp_cr_license")

tasks.register('buildAgentMainDex') {
    doLast {
        def tempOutput = agentMainTempOutputDir.get().asFile.absolutePath
        def helperClasses = fileTree("${classesDir}/com/microsoft/xbox/idp/telemetry/helpers") {
            include '**/*.class'
        }.files.collect { it.absolutePath }.sort()
        def firebaseIidClasses = fileTree("${classesDir}/com/google/firebase/iid") {
            include 'FirebaseInstanceId*.class'
        }.files.collect { it.absolutePath }.sort()
        def firebaseAppClasses = fileTree("${classesDir}/com/google/firebase") {
            include 'FirebaseApp*.class'
            include 'FirebaseOptions*.class'
        }.files.collect { it.absolutePath }.sort()
        def extraClasses = [
                "${classesDir}/com/mojang/minecraftpe/AgentMainActivity.class",
                "${classesDir}/com/mojang/minecraftpe/GameContextBridge.class",
                "${classesDir}/com/google/android/gms/common/internal/StringResourceValueReader.class",
                "${classesDir}/com/microsoft/onlineid/internal/PackageInfoHelper.class",
                "${classesDir}/com/microsoft/onlineid/internal/Resources.class",
                "${classesDir}/com/microsoft/xbox/idp/telemetry/utc/model/UTCAdditionalInfoModel.class"
        ]
        def dexInputs = extraClasses + helperClasses + firebaseAppClasses + firebaseIidClasses

        file(tempOutput).mkdirs()

        println "Generating dex for: ${outputDir}/AgentMainActivity.dex"

        providers.exec { spec ->
            spec.commandLine([d8Executable(), "--output", tempOutput] + dexInputs)
        }.result.get()

        copy {
            from "${tempOutput}/classes.dex"
            into outputDir
            rename { "AgentMainActivity.dex" }
        }
        delete file(tempOutput)
    }
}

tasks.register('buildCrackedLicenseDex') {
    doLast {
        def tempOutput = crackedLicenseTempOutputDir.get().asFile.absolutePath

        file(tempOutput).mkdirs()

        println "Generating dex for: ${outputDir}/CrackedLicense.dex"

        providers.exec { spec ->
            spec.commandLine(
                    d8Executable(),
                    "--output", tempOutput,
                    "${classesDir}/com/mojang/minecraftpe/store/amazonappstore/AmazonAppStore.class",
                    "${classesDir}/com/mojang/minecraftpe/store/googleplay/GooglePlayStore.class"
            )
        }.result.get()
        copy {
            from "${tempOutput}/classes.dex"
            into outputDir
            rename { "CrackedLicense.dex" }
        }
        delete file(tempOutput)
    }
}

tasks.register('buildDexDebug') {
    /* println "========"
    println "[agent_main info]:"
    // println "Project Path: ${projectDir}"
    // println "Working directory: ${classesDir}"
    // println "Output directory: ${outputDir}"
    // println "Android SDK Path: ${getSdkPath()}"
    println "Using d8 from: ${d8Executable()}"
    println "========" */

    dependsOn buildAgentMainDex, buildCrackedLicenseDex
}

afterEvaluate {
    tasks.named("compileDebugJavaWithJavac") {
        it.finalizedBy(buildDexDebug)
    }
    tasks.named("compileReleaseJavaWithJavac") {
        it.finalizedBy(buildDexDebug)
    }
}
