plugins {
    id 'com.android.library'
}

android {
    namespace "com.mojang.minecraftpe"
    compileSdkVersion 35 // Android 15

    defaultConfig {
        minSdkVersion 25

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        targetSdk 35
    }
    testOptions {
        targetSdk 35
    }
}

dependencies {
}

String getSdkPath() {
    File localPropertiesFile = new File(project.rootDir, "local.properties")
    Properties localProperties = new Properties()
    localProperties.load(new FileReader(localPropertiesFile))
    return localProperties.getProperty("sdk.dir")
}

String d8Executable() {
    def buildToolsVersion = "36.0.0" // Check you version

    def sdkPath = getSdkPath()
    def buildToolsDir = "${sdkPath}/build-tools/${buildToolsVersion}/"
    return System.properties['os.name'].toLowerCase().contains("windows") ?
            "${buildToolsDir}d8.bat" : "${buildToolsDir}d8"
}

def classesDir = "${project.buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes"
def outputDir = "${project.rootDir}/endercore/src/main/assets/endercore/android"

tasks.register('buildAgentMainDex') {
    doLast {
        def tempOutput = "${project.buildDir}/d8temp_agent_main"

        file(tempOutput).mkdirs()

        println "Generating dex for: ${outputDir}/AgentMainActivity.dex"

        providers.exec { spec ->
            spec.commandLine(
                    d8Executable(),
                    "--output", tempOutput,
                    "${classesDir}/com/mojang/minecraftpe/AgentMainActivity.class"
            )
        }.result.get()

        copy {
            from "${tempOutput}/classes.dex"
            into outputDir
            rename { "AgentMainActivity.dex" }
        }
        delete file(tempOutput)
    }
}

tasks.register('buildCrackedLicenseDex') {
    doLast {
        def tempOutput = "${project.buildDir}/d8temp_cr_license"

        file(tempOutput).mkdirs()

        println "Generating dex for: ${outputDir}/CrackedLicense.dex"

        providers.exec { spec ->
            spec.commandLine(
                    d8Executable(),
                    "--output", tempOutput,
                    "${classesDir}/com/mojang/minecraftpe/store/amazonappstore/AmazonAppStore.class",
                    "${classesDir}/com/mojang/minecraftpe/store/googleplay/GooglePlayStore.class"
            )
        }.result.get()
        copy {
            from "${tempOutput}/classes.dex"
            into outputDir
            rename { "CrackedLicense.dex" }
        }
        delete file(tempOutput)
    }
}

tasks.register('buildDexDebug') {
    /* println "========"
    println "[agent_main info]:"
    // println "Project Path: ${projectDir}"
    // println "Working directory: ${classesDir}"
    // println "Output directory: ${outputDir}"
    // println "Android SDK Path: ${getSdkPath()}"
    println "Using d8 from: ${d8Executable()}"
    println "========" */

    dependsOn buildAgentMainDex, buildCrackedLicenseDex
}

afterEvaluate {
    tasks.named("compileDebugJavaWithJavac") {
        it.finalizedBy(buildDexDebug)
    }
    tasks.named("compileReleaseJavaWithJavac") {
        it.finalizedBy(buildDexDebug)
    }
}
